### ISSUE TITLE
Monokai theme looks weird. Can this be fixed if its easy please?

### ISSUE THREAD

**Issue by Void48** [TcNobo/TcNo-Acc-Switcher-Themes#3]
![image](https://user-images.githubusercontent.com/85196642/152663174-5c0d6924-e1dd-46bf-bb63-d2cd16049fa9.png)

**Comment by TCNOco** [comment]
Yes I'm aware of this. Was just focusing on major issues stopping platforms working properly :)

**Comment by TCNOco** [comment]
Fixed. You should see the changes when the next update is pushed - Hopefully in a few hours.
